version: '3.1'
services:
  db:
    image: mysql
    container_name: mydb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD : mypassword
    ports:
      - 3306:3306