Mind Map generated by NB MindMap plugin   
> __version__=`1.1`,showJumps=`true`
---

# QR code service

## Rest API
> collapsed=`true`


### POST /rest/v1/qrcode/generate

## Documentation
> collapsed=`true`,leftSide=`true`


### How to Generate QR Code in Java Spring Boot
- LINK
<pre>https://medium.com/nerd-for-tech/how-to-generate-qr-code-in-java-spring-boot-134adb81f10d</pre>

### Generating QR Code in Java
- LINK
<pre>https://www.javatpoint.com/generating-qr-code-in-java</pre>
